Added a critter editor (all variants)
CaveStoryModdingCommunity/FreewareHacks pull request #11
Opened 2023-06-24 16:03 UTC by takimaya

contains all regular critters, power critters and misery spawns

2023-07-04 00:29 UTC, Brayconn requested changes
This looks great! A few small changes:
1. Can this be split up into a separate file for each critter? I think it'd be a bit more manageable to use that way.
2. For things like Terminal Velocity, where there's one value for comparison check and one that actually does the setting, could they be labeled as such? Something like "Terminal Velocity (check)" and "Terminal Velocity (set)". Probably still want to keep the warning about keeping them the same, but it's better to document which each one is.
3. There are a few typos/weird wordings in the descriptions
In the Purple Critter description:
> ... divided by a predetermined divident leaves a specific remainder.

First, it's "dividend", not "divident".
Second, this could maybe be better explained by describing it in terms of a modulo?
b. In the Orange Critter description:
> Orange critters aren't visible, do not deal any damage or move before they "activate" (it takes them 16 frames by default).

This can probably be replaced with
> Orange Critters are invisible/intangible for the first 16 frames (by default) of their existence.

Also...
> ... and disappear after jumping a certain amount of times (plus one).

This should probably say "ticks" not "times".

2023-07-04 07:37 UTC, Brayconn commented
> rephrasing that bit could work, assuming modulo is a term most people know

tbh, that suggestion is a bit more experimental. Once you tell people what the modulo/modulus is, they get it pretty quick, but, unless you're already a math/programming nerd, you might not have heard it before.
Best case scenario is that it makes the explanation super clear and concise, but it'll need some work.

>        but surprisingly enough, you are wrong about the ticks! they actually count how many times they've performed a jump before deciding to leave the world forever

Oh dang, I completely missed the word "jumps", nvm that suggestion :colondead:

Though, I guess it could just say
> ... and disappear after a certain amount of jumps (plus one).

2023-07-04 12:28 UTC, takimaya commented
yeah this should be fine, i changed the wording a bit, added notes on gravity in all cases and split the .xml into single NPCs

2023-09-24 00:58 UTC, Brayconn approved these changes

2023-10-14 05:27 UTC, merged